config/routes.rb
Rails.application.routes.draw do

  resources :to_do_lists do
    resources :to_do_items do
    	member do
    		patch :complete
    	end
    end
  end
  
  root "to_do_lists#index"
end

app/models/to_do_item.rb
class ToDoItem < ActiveRecord::Base
  belongs_to :to_do_list

  def completed?
  	!completed_at.blank?
  end
end

app/models/to_do_list.rb
class ToDoList < ActiveRecord::Base
  has_many :to_do_items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/to_do_items_controller.rb
class ToDoItemsController < ApplicationController
	before_action :set_to_do_list
	before_action :set_to_do_item, except: [:create]

	def create
		@to_do_item = @to_do_list.to_do_items.create(to_do_item_params)
		redirect_to @to_do_list
	end

	def destroy
		if @to_do_item.destroy
			flash[:success] = "sildim gitti"
		else
			flash[:error] = "silinmedi"
		end
		redirect_to @to_do_list
	end

	def complete
		@to_do_item.update_attribute(:completed_at, Time.now)
		redirect_to @to_do_list, notice: "To do item completed"
	end

	private

	def set_to_do_list
		@to_do_list = ToDoList.find(params[:to_do_list_id])
	end

	def set_to_do_item
		@to_do_item = @to_do_list.to_do_items.find(params[:id])
	end

	def to_do_item_params
		params[:to_do_item].permit(:content)
	end

end

app/controllers/to_do_lists_controller.rb
class ToDoListsController < ApplicationController
  before_action :set_to_do_list, only: [:show, :edit, :update, :destroy]

  # GET /to_do_lists
  # GET /to_do_lists.json
  def index
    @to_do_lists = ToDoList.all
  end

  # GET /to_do_lists/1
  # GET /to_do_lists/1.json
  def show
  end

  # GET /to_do_lists/new
  def new
    @to_do_list = ToDoList.new
  end

  # GET /to_do_lists/1/edit
  def edit
  end

  # POST /to_do_lists
  # POST /to_do_lists.json
  def create
    @to_do_list = ToDoList.new(to_do_list_params)

    respond_to do |format|
      if @to_do_list.save
        format.html { redirect_to @to_do_list, notice: 'To do list was successfully created.' }
        format.json { render :show, status: :created, location: @to_do_list }
      else
        format.html { render :new }
        format.json { render json: @to_do_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /to_do_lists/1
  # PATCH/PUT /to_do_lists/1.json
  def update
    respond_to do |format|
      if @to_do_list.update(to_do_list_params)
        format.html { redirect_to @to_do_list, notice: 'To do list was successfully updated.' }
        format.json { render :show, status: :ok, location: @to_do_list }
      else
        format.html { render :edit }
        format.json { render json: @to_do_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /to_do_lists/1
  # DELETE /to_do_lists/1.json
  def destroy
    @to_do_list.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'To do list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_to_do_list
      @to_do_list = ToDoList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def to_do_list_params
      params.require(:to_do_list).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/to_do_items_helper.rb
module ToDoItemsHelper
end

app/helpers/to_do_lists_helper.rb
module ToDoListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Raleway:400,700' rel='stylesheet' type='text/css'>
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
</head>
<body>

<div class="container">
	<%= yield %>
</div>

</body>
</html>

app/views/to_do_items/_form.html.erb
<%= form_for([@to_do_list, @to_do_list.to_do_items.build]) do |f| %>
  <%= f.text_field :content, placeholder: "New To_do" %>
  <%=f.submit %>
<% end %>

app/views/to_do_items/_to_do_item.html.erb
<div class="row clearfix">
	<% if to_do_item.completed? %>
		<div class="complete">
    <%= link_to complete_to_do_list_to_do_item_path(@to_do_list, to_do_item.id), method: :patch do%>
		<i style= "opacity: 0.4;" class="fa fa-check"></i>
		<% end %>
  </div>
  <div class="to_do_item">
    <p style= "opacity: 0.4;"><strike><%= to_do_item.content %></strike></p>
  </div>
  <div class="trash">
    <%= link_to to_do_list_to_do_item_path(@to_do_list, to_do_item.id),method: :delete, data: { confirm: "emin misiniz?" } do %>
		 <i class="fa fa-trash"></i>

      <%end%>

  </div>
    <% else %>
    <div class="complete">
			<%= link_to complete_to_do_list_to_do_item_path(@to_do_list, to_do_item.id), method: :patch do%>
			<i class="fa fa-check"></i>
			<% end %>
    </div>
    <div class="to_do_item">
      <p><%= to_do_item.content %></p>
    </div>
    <div class="trash">
			<%= link_to to_do_list_to_do_item_path(@to_do_list, to_do_item.id),method: :delete, data: { confirm: "emin misiniz?" } do %>
			 <i class="fa fa-trash"></i>
			 <% end %>
    </div>
    <% end %>
</div>

app/views/to_do_lists/_form.html.erb
<%= form_for(@to_do_list) do |f| %>
  <% if @to_do_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@to_do_list.errors.count, "error") %> prohibited this to_do_list from being saved:</h2>

      <ul>
      <% @to_do_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/to_do_lists/edit.html.erb
<h1 class="to_do_list_title">Edit ToDo List</h1>

<div class="forms">
	<%= render 'form' %>
</div>

<div class="links">
	<%= link_to 'Cancel', to_do_lists_path %>
</div>

app/views/to_do_lists/index.html.erb
<% @to_do_lists.each do |to_do_list| %>
<div class="index_row clearfix">
  <h2 class="to_do_list_title>"><%= link_to to_do_list.title, to_do_list%></h2>
  <p class="to_do_list_sub_title"><%= to_do_list.description%></p>
</div>
<% end %>

<div class="links">
  <%= link_to "New Todo List", new_to_do_list_path %>

</div>

app/views/to_do_lists/new.html.erb
<h1 class="to_do_list_title">New ToDo List</h1>

<div class="forms">
	<%= render 'form' %>
</div>

<div class="links">
	<%= link_to 'Back', to_do_lists_path %>
</div>

app/views/to_do_lists/show.html.erb
<p id="notice"><%= notice %></p>
 
<h2 class="to_do_list_title"><%= @to_do_list.title %></h2>
<p class="to_do_list_sub_title"><%= @to_do_list.description %></p>

<div id="to_do_items_wrapper">
	<%= render @to_do_list.to_do_items %>
	<div id="form">
		<%= render "to_do_items/form" %>
	</div>
</div>

<div class="links">
	<%= link_to 'Edit', edit_to_do_list_path(@to_do_list) %> |
	<%= link_to 'Delete', to_do_list_path(@to_do_list), method: :delete, data: { confirm: "Are you sure?" }
 %> |
  <%= link_to 'Back', to_do_lists_path %>
</div>